# Default values for opensds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  osdsdb: quay.io/coreos/etcd:latest
  osdslet: opensdsio/opensds-controller:latest
  osdsdock: opensdsio/opensds-dock:latest
# ImagePullPolicy: valid values are "IfNotPresent", "Never", and "Always"
imagePullPolicy: IfNotPresent
# ImageRestartPolicy: valid values are "Never", and "Always"
imageRestartPolicy: Never
