dist: xenial
sudo: required

language: go
go_import_path: github.com/opensds/opensds

go:
  - 1.12.x
  - 1.13.x
  - tip

env:
  - TARGET=amd64
    GO111MODULE=on

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential gcc
  - sudo apt-get install -y librados-dev librbd-dev
  - sudo apt-get install -y lvm2 tgt open-iscsi
  - sudo docker pull p1c2u/openapi-spec-validator
  - sudo pip install robotframework


matrix:
  fast_finish: true
  allow_failures:
  - go: tip
  exclude:


install:
  # Build OpenSDS Controller source code
  - make all
  # Start lvm e2e test
  # - split_line "Start lvm e2e test"
  - sudo install/devsds/uninstall.sh --purge
  - sudo install/devsds/install.sh
  - export OPENSDS_AUTH_STRATEGY=noauth
  - export OPENSDS_ENDPOINT=http://localhost:50040
  - sudo echo $(ps -ef |grep osds)

script:
  - export PYTHONPATH=/home/travis/gopath/src/github.com/opensds/opensds/install/CI/
  - sudo cp build/out/bin/osdsctl /usr/local/bin/
  - sudo vgs
  - sudo vgdisplay
  - robot install/CI/hotpot.robot
  - sudo cat /home/travis/gopath/src/github.com/opensds/opensds/output.xml
  - ./install/CI/coverage
  - ./install/CI/test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  # Clean OpenSDS Controller built data
  - make clean
