dist: trusty
sudo: required 

language: go
go_import_path: github.com/opensds/opensds

go:
  - 1.7
  - 1.8
  - tip

env:
  matrix:
   - TARGET=amd64
   - TARGET=arm64
   - TARGET=arm
   - TARGET=386
   - TARGET=ppc64le

before_install:
  - sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
  - sudo apt-get install glide librados-dev librbd-dev -y 

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  exclude:
  - go: tip
    env: TARGET=arm
  - go: tip
    env: TARGET=arm64
  - go: tip
    env: TARGET=386
  - go: tip
    env: TARGET=ppc64le

script:
  - glide install
  - go build ./cmd/osdslet && go build ./cmd/osdsdock
  - go test -v github.com/opensds/opensds/cmd/osdslet -cover && go test -v github.com/opensds/opensds/cmd/osdsdock -cover
  - go test -v github.com/opensds/opensds/pkg/... -cover
  - go test -v github.com/opensds/opensds/contrib/... -cover
