dist: xenial
sudo: required

language: go
go_import_path: github.com/sodafoundation/api

go:
  - 1.12.x
  - 1.13.x
  - tip

env:
  - TARGET=amd64
    GO111MODULE=on

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential gcc
  - sudo apt-get install -y librados-dev librbd-dev
  - sudo apt-get install -y lvm2 tgt open-iscsi
  - sudo docker pull p1c2u/openapi-spec-validator
  - go get -v github.com/onsi/gomega
  - go get -v github.com/onsi/ginkgo/ginkgo

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
  exclude:


install:
  # TODO: Remove once source code is fixed for sodafoundation
  - ln -s $GOPATH/src/sodafoundation $GOPATH/src/opensds
  # Build OpenSDS Controller source code
  - make osdsapiserver
  - make osdsctl

script:
  - ./install/CI/coverage
  - ./install/CI/test

after_failure:
  - for v in /var/log/opensds/*.log ; do
    echo $v logtail ======================== ; tail -100 $v ;
    done

after_success:
  - bash <(curl -s https://codecov.io/bash)
  # Clean OpenSDS Controller built data
  - make clean
