kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "fullname" . }}-opensds
  labels:
    app: {{ template "fullname" . }}-opensds
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-opensds
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-opensds
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
        - name: osdsdb
          image: {{ .Values.image.osdsdb }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            - name: etcd-cert-dir
              mountPath: /etc/ssl/certs
        - name: osdslet
          image: {{ .Values.image.osdslet }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            - name: opensds-conf-dir
              mountPath: /etc/opensds
        - name: osdsdock
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: {{ .Values.image.osdsdock }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            - name: opensds-conf-dir
              mountPath: /etc/opensds
              mountPropagation: "Bidirectional"
      volumes:
        - name: etcd-cert-dir
          hostPath:
            path: /usr/share/ca-certificates/
            type: Directory
        - name: opensds-conf-dir
          hostPath:
            path: /etc/opensds
            type: Directory
