kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-opensds
  labels:
    app: {{ template "fullname" . }}-opensds
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ template "fullname" . }}-opensds
  ports:
  - protocol: TCP
    port: 50040
    targetPort: 50040
