name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      GO111MODULE: on
      TARGET: amd64
        
    strategy:
      matrix:
        go-version: [1.13.x]
        os: [ubuntu-18.04, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout project  
      uses: actions/checkout@v2
    
    - name: Install Pre-requisites
      run: sudo apt-get update && sudo apt-get install -y git make curl wget build-essential gcc librados-dev librbd-dev  lvm2 tgt open-iscsi
      
    - name: Build Controller Source
      run: make osdsapiserver && make osdsctl

    - name: Run CI scripts for Testing
      run: ./install/CI/coverage && ./install/CI/test
    
    - name: After success run Codecov Coverage tool.
      run: bash <(curl -s https://codecov.io/bash)
    
    - name: Clean SODA Controller built data
      run: make clean
